exclude: '__snapshots__|^vendor/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/cpendery/asort
    rev: v0.1.3
    hooks:
      - id: asort
        files: '__init__\.py$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: nox -s precommit_pyright --
        language: python
        language_version: '3.11'
        additional_dependencies: [nox]
        types_or: [python, pyi]
        require_serial: true
