modid = "hexdoc"
default_lang = "en_us"

resource_dirs = [  # top takes priority
    ".hexdoc_minecraft/1.20.2/resources",
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_minecraft/_export/generated"

[minecraft_assets]
# https://github.com/PrismarineJS/minecraft-assets/tree/a14c64362abe4a12c2dfd87f8d1673af9d1b09f4/data/1.20.2
ref = "a14c64362abe4a12c2dfd87f8d1673af9d1b09f4"
version = "1.20.2"
