modid = "{{ cookiecutter.modid }}"
book = "{{ cookiecutter.book_id }}"
default_lang = "en_us"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    "{_common.src}/generated/resources",
    {% if cookiecutter.multiloader -%}
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
    {%- endif %}
    { modid="hexcasting" },
    { modid="hexdoc" },
]
export_dir = "{{ cookiecutter.__export_root }}/generated"

[extra.hexcasting]
# regexes for parsing pattern registry files - try uncommenting a different one if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"

# Hex Casting (0.11.0)
{{ "# " if cookiecutter.pattern_regex != "hex_latest" }}_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }

# Hex Casting (0.10.3)
{{ "# " if cookiecutter.pattern_regex != "hex_0.10.3" }}_pattern_regex = { "!Raw"='HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?' }

# Hexal (0.3.0)
{{ "# " if cookiecutter.pattern_regex != "hexal_0.3.0" }}_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }

# Hexal (0.2.18)
{{ "# " if cookiecutter.pattern_regex != "hexal_0.2.18" }}_pattern_regex = { "!Raw"='(?s-m:HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\),[^,]+?(?:makeConstantOp|Op\w+).*?(?P<is_per_world>\btrue)?\)(?:[^\)]+?\bval\b|(?:(?!\bval\b)(?:.))+$))' }

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/{{ cookiecutter.pattern_registry }}"
regex = "{^_pattern_regex}"

[minecraft_assets]
# https://github.com/PrismarineJS/minecraft-assets/tree/83e2169afbbce40990d69fc53e5962e4a793d467/data/1.19.1
ref = "83e2169afbbce40990d69fc53e5962e4a793d467"
version = "1.19.1"

[template]
icon = "icon.png"
include = [
    "{{ cookiecutter.modid }}",
    "hexcasting",
    "patchouli",
    "hexdoc",
]

[template.args]
mod_name = "{{ cookiecutter.mod_display_name }}"
author = "{{ cookiecutter.author }}"
show_landing_text = false

# platforms

[_common]
src = "../{{ 'common/src' if cookiecutter.multiloader else 'src' }}"
package = "{src}/main/{{ cookiecutter.java_lang }}/{{ cookiecutter.java_package }}"

{% if cookiecutter.multiloader -%}
[_fabric]
src = "../fabric/src"
package = "{src}/main/{{ cookiecutter.java_lang }}/{{ cookiecutter.java_package }}/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/{{ cookiecutter.java_lang }}/{{ cookiecutter.java_package }}/forge"
{%- endif %}
