name: Deploy docs to GitHub Pages

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Nox
        run: pip install nox

      - name: Run pdoc
        timeout-minutes: 1
        run: nox --session pdoc -- --output-directory docs/api/

      # TODO: move this into a separate repo or something, and use the actual hexdoc.yml action
      - name: Generate demo book
        run: |
          nox --session dummy_setup
          nox --session dummy_hexdoc -- build
          nox --session dummy_hexdoc -- merge
          mv .hexdoc/dummy_book/_site/dst/docs docs/demo

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - id: deploy-pages
        uses: actions/deploy-pages@v3
