name: "[Reusable] Build and publish a hexdoc plugin"

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to install
        type: string
        required: true
      release:
        description: If the book should be written to the release path or the latest path
        type: boolean
        required: true
      props:
        description: Path to your props file (hexdoc.toml or properties.toml)
        type: string
        required: false
      pip-extras:
        description: Pip extras for your package (eg. [dev])
        type: string
        required: false
      pages-url:
        type: string
        default: https://example.com # lie
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      release:
        description: Value of inputs.release for convenience
        value: ${{ inputs.release }}

permissions:
  contents: read

env:
  HEXDOC_PROPS: ${{ inputs.props }}
  HEXDOC_RELEASE: ${{ inputs.release }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: read
      pages: read
    outputs:
      pages-url: ${{ steps.export.outputs.pages-url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install display server
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xvfb

      - name: Install Python packages
        run: pip install -e .${{ inputs.pip-extras }}

      - name: Build web book
        id: export
        env:
          GITHUB_PAGES_URL: ${{ inputs.pages-url }}
        run: |
          hexdoc build
          hatch build --clean

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Add job summary
        run: echo "Built version \`$(hatch version)\` from commit \`$(git rev-parse --short "$GITHUB_SHA")\`." >> $GITHUB_STEP_SUMMARY
