name: "[Reusable] Build and publish a hexdoc project"

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to install
        type: string
        required: true
      release:
        description: If the book should be written to the release path or the latest path
        type: boolean
        required: true
      props:
        description: Path to your props file (hexdoc.toml or properties.toml)
        type: string
        required: false
      bump-version-segment:
        description: Version segment to bump with Hatch
        type: string
        required: false
      pip-extras:
        description: Pip extras for your package (eg. [dev])
        type: string
        required: false
    outputs:
      pages-url:
        description: Current GitHub Pages url for this repo.
        value: ${{ jobs.build.outputs.pages-url }}

permissions:
  contents: read

env:
  HEXDOC_RELEASE: ${{ inputs.release }}
  HEXDOC_PROPS: ${{ inputs.props }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pages: read
    outputs:
      pages-url:  ${{ steps.get-url.outputs.pages-url }}
      matrix:     ${{ steps.list-langs.outputs.matrix }}
      branch:     ${{ steps.parse-inputs.outputs.branch }}
      props-path: ${{ steps.parse-inputs.outputs.props-path }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xvfb

      - name: Get Pages url
        id: get-url
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo "pages-url=$url" >> "$GITHUB_OUTPUT"
          echo "GITHUB_PAGES_URL=$url" >> "$GITHUB_ENV"

      - name: Parse inputs
        id: parse-inputs
        run: |
          if [[ ${{ inputs.checkout }} == true ]]; then
            branch='${{ inputs.branch }}'
            props_path=_checkout/${{ inputs.props-path }}
            echo "HATCH_GRADLE_DIR=_checkout" >> "$GITHUB_ENV"
          else
            branch=none
            props_path=${{ inputs.props-path }}
          fi

          echo "HEXDOC_PROPS=$props_path" >> "$GITHUB_ENV"

          echo "branch=$branch"         >> "$GITHUB_OUTPUT"
          echo "props-path=$props_path" >> "$GITHUB_OUTPUT"

      - name: Checkout input branch
        if: steps.parse-inputs.outputs.branch != 'none'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.parse-inputs.outputs.branch }}
          path: _checkout

      - name: Install docgen from source
        run: pip install .${{ inputs.pip-extras }} hatch

      - name: List book languages
        id: list-langs
        run: |
          echo "matrix=$(hexdoc list-langs)" >> "$GITHUB_OUTPUT"
          if [[ $RUNNER_DEBUG ]]; then
            tree -I '__pycache__|Common|Fabric|Forge|venv'
          fi

      - name: Export hexdoc resources
        run: xvfb-run --auto-servernum hexdoc export

      - name: Upload hexdoc cache artifact
        uses: actions/upload-artifact@v3
        with:
          name: hexdoc-cache
          path: .hexdoc

      - name: Bump version
        if: inputs.bump-version-segment
        run: hatch version "${{ inputs.bump-version-segment }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build web book from ${{ github.ref }}

      - name: Build package
        run: hatch build

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Copy build to Pages
        if: env.UPDATE_LATEST
        run: |
          mkdir -p _site/v/latest
          cp -r dist _site/v/latest/dist

      - name: Upload temporary Pages artifact
        if: env.UPDATE_LATEST
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-tmp
          path: _site

      - name: Add job summary
        run: echo "Built version \`$(hatch version)\` from commit \`$(git rev-parse --short "$GITHUB_SHA")\`." >> $GITHUB_STEP_SUMMARY

  render:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: ${{ matrix.lang.continue_on_error }}

    strategy:
      fail-fast: false
      matrix:
        lang: ${{ fromJson(needs.build.outputs.matrix) }}

    env:
      GITHUB_PAGES_URL: ${{ needs.build.outputs.pages-url }}
      HEXDOC_PROPS: ${{ needs.build.outputs.props-path }}
      RENDER_CMD:

    steps:
      - uses: actions/checkout@v3
      - uses: object-Object/hexdoc/.github/actions/install-artifact-wheel@v0
        with:
          name: hexdoc-build
          python-version: ${{ inputs.python-version }}
          pip-extras: ${{ inputs.pip-extras }}

      - name: Download hexdoc cache artifact
        uses: actions/download-artifact@v3
        with:
          name: hexdoc-cache
          path: .hexdoc

      - name: Generate web book
        id: gen-normal
        continue-on-error: true
        run: hexdoc render _site --lang ${{ matrix.lang.value }} --clean

      - name: Generate web book with missing translations
        if: steps.gen-normal.outcome == 'failure'
        run: hexdoc render _site --lang ${{ matrix.lang.value }} --clean --allow-missing

      - name: Upload temporary Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-tmp
          path: _site

      - name: Create annotation if the first generate step failed
        if: steps.gen-normal.outcome == 'failure'
        run: |
          echo "::error::${{ matrix.lang.value }} is missing some i18n keys."

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [build, render]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: object-Object/hexdoc
          path: _checkout_object-Object_hexdoc
      - uses: ./_checkout_object-Object_hexdoc/.github/actions/install-artifact-wheel
        with:
          name: hexdoc-build
          python-version: ${{ inputs.python-version }}
          pip-extras: ${{ inputs.pip-extras }}

      - name: Checkout current Pages
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: _site/dst

      - name: Download temporary Pages artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages-tmp
          path: _site/src/docs

      - name: Add new docs to site
        run: hexdoc merge --src _site/src/docs --dst _site/dst/docs

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site/dst/docs
          target-folder: docs
